behaviors:
  ppo_behavior:
    trainer_type: ppo
    max_steps: 1000000
    time_horizon: 128
    hyperparameters:
      batch_size: 128 
      learning_rate: 3.0e-4
      beta: 0.005
    reward_signals:
      curiosity:
        strength: 0.05
        gamma: 0.99
        encoding_size: 64