behaviors:
  ppo_behavior:
    trainer_type: ppo
    max_steps: 50000
    time_horizon: 128
    threaded: true
    hyperparameters:
      buffer_size: 2048
      batch_size: 128
      learning_rate: 3.0e-4
      beta: 0.03
    reward_signals:
      curiosity:
        strength: 0.1
        gamma: 0.99
        encoding_size: 64
      extrinsic:
        strength: 1.0
        gamma: 0.99
        normalize: true